baseurl: https://tuengominh.github.io

exclude: ['README.md']
collections:
  project:
    output: true
  tag:
    output: true
  tinkering:
    output: true
  tldr:
    output: true
  
plugins:
  - jemoji